module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'chore',
        'docs',
        'test',
        'refactor',
        'ci',
        'style',
        'perf',
        'revert',
        'build',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'root',
        'workspace',
        'packages',
        'client',
        'web',
        'desktop',
        'mobile',
        'api',
        'contracts',
        'domain',
        'api-client',
        'client-core',
        'client-ui-web',
        'tauri',
        'capacitor',
        'android',
        'ios',
        'docs',
      ],
    ],
    'scope-empty': [2, 'never'],
    'subject-empty': [2, 'never'],
    'subject-case': [0],
  },
};
